import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';

import { useAuth } from '../../context/AuthContext.jsx';
import { deleteBoardAttachment, deleteBoardComment, deleteBoardPost, getAttachmentDownloadUrl, getBoardOverview, getBoardPost, getBoardReactions, saveBoardComment, toggleBoardReaction, uploadBoardAttachment } from '../../services/boardService.js';

export default function PostDetailPage() {
  const { boardSlug, postId } = useParams(); const navigate = useNavigate(); const auth = useAuth();
  const [data, setData] = useState(null); const [overview, setOverview] = useState(null); const [reactions, setReactions] = useState({ counts: {}, mine: [] }); const [error, setError] = useState(''); const [replyTo, setReplyTo] = useState(null);
  const load = () => Promise.all([getBoardPost(postId), getBoardOverview(boardSlug), getBoardReactions(postId).catch(() => ({ counts: {}, mine: [] }))]).then(([postData, boardData, reactionData]) => { setData(postData); setOverview(boardData); setReactions(reactionData); setError(''); }).catch(() => setError('게시글을 볼 권한이 없거나 글을 찾을 수 없습니다.'));
  useEffect(() => { load(); }, [boardSlug, postId]);
  if (error) return <div className="gw-route-state"><div className="gw-notice gw-notice--warning" role="alert">{error}<br /><Link to="/boards">게시판으로</Link></div></div>;
  if (!data || !overview) return <p className="gw-empty-state">게시글을 불러오고 있습니다.</p>;
  const submitComment = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await saveBoardComment({ postId, parentCommentId: replyTo, content: form.get('content'), isAnonymous: form.get('anonymous') === 'on' }); event.currentTarget.reset(); setReplyTo(null); load(); } catch { setError('댓글을 저장하지 못했습니다.'); } };
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; try { await uploadBoardAttachment({ boardId: data.post.board_id, postId, file, userId: auth.user.id, maxSizeMb: overview.board.settings.max_file_size_mb }); load(); } catch (uploadError) { setError(uploadError.message); } event.target.value = ''; };
  return <article className="gw-page" aria-labelledby="post-title"><header className="gw-post-header"><div><span>{data.post.is_notice ? '공지' : '게시글'}</span><h1 id="post-title">{data.post.title}</h1><p>{data.post.author_name} · {new Date(data.post.created_at).toLocaleString('ko-KR')} · 조회 {data.post.view_count}</p></div><div className="gw-admin-actions">{data.post.can_edit && <Link className="gw-secondary-button" to={`/boards/${boardSlug}/posts/${postId}/edit`}>수정</Link>}{data.post.can_delete && <button className="gw-secondary-button gw-secondary-button--danger" type="button" onClick={async () => { if (window.confirm('이 게시글을 삭제하시겠습니까?')) { await deleteBoardPost(postId); navigate(`/boards/${boardSlug}`); } }}>삭제</button>}</div></header><section className="gw-post-content"><p>{data.post.content}</p></section>
    {overview.board.settings.allow_reactions && <section className="gw-reactions" aria-label="게시글 반응">{[['like','좋아요'],['helpful','도움돼요'],['support','응원해요']].map(([type, label]) => <button key={type} type="button" aria-pressed={reactions.mine.includes(type)} onClick={async () => setReactions(await toggleBoardReaction(postId, type))}>{label} {reactions.counts[type] ?? 0}</button>)}</section>}
    {overview.board.settings.allow_attachments && <section className="gw-attachment-section"><h2>첨부파일</h2><div className="gw-attachment-list">{data.attachments.map((item) => <div key={item.id}><button type="button" onClick={async () => window.open(await getAttachmentDownloadUrl(item.id), '_blank', 'noopener')}>{item.original_name} <span>{Math.ceil(item.file_size / 1024)}KB</span></button>{data.post.can_edit && <button type="button" onClick={async () => { await deleteBoardAttachment(item.id); load(); }} aria-label={`${item.original_name} 삭제`}>삭제</button>}</div>)}</div>{overview.permissions.upload && <label className="gw-file-button">파일 첨부<input type="file" onChange={upload} /></label>}</section>}
    {overview.board.settings.allow_comments && <section className="gw-comments"><h2>댓글</h2>{data.comments.map((comment) => <article key={comment.id} className={comment.parent_comment_id ? 'is-reply' : ''}><header><strong>{comment.author_name}</strong><time>{new Date(comment.created_at).toLocaleString('ko-KR')}</time></header><p>{comment.content}</p><div>{overview.permissions.comment && overview.board.settings.allow_replies && <button type="button" onClick={() => setReplyTo(comment.id)}>답글</button>}{comment.can_delete && <button type="button" onClick={async () => { await deleteBoardComment(comment.id); load(); }}>삭제</button>}</div></article>)}{overview.permissions.comment && <form className="gw-comment-form" onSubmit={submitComment}><label className="gw-field"><span>{replyTo ? '답글' : '댓글'}</span><textarea name="content" required /></label>{overview.board.settings.allow_anonymous && <label><input type="checkbox" name="anonymous" /> 익명</label>}<button className="gw-primary-button" type="submit">등록</button></form>}</section>}
  </article>;
}
